#include <limit/suites/close_limit_buy_tests.hpp>
#include <limit/suites/close_limit_sell_tests.hpp>
#include <limit/suites/close_tests.hpp>
#include <limit/suites/create_limit_buy_tests.hpp>
#include <limit/suites/create_limit_sell_tests.hpp>
#include <limit/suites/fill_buy_order_tests.hpp>
#include <limit/suites/fill_sell_order_tests.hpp>
#include <limit/suites/on_transfer_tests.hpp>
#include <limit/suites/open_tests.hpp>
#include <limit/suites/part_fill_buy_order_tests.hpp>
#include <limit/suites/part_fill_sell_order_tests.hpp>
#include <limit/suites/withdraw_tests.hpp>